# Generated by Django 4.2.4 on 2023-09-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_is_active_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_client",
            field=models.BooleanField(null=True, verbose_name="user_type"),
        ),
    ]
