# Generated by Django 4.2.4 on 2023-09-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_is_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=False, verbose_name="online_status"),
        ),
    ]
