# Generated by Django 4.2.4 on 2023-09-15 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_user_profile_image_therapyrequests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapyrequests",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_requests",
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
        migrations.AlterField(
            model_name="therapyrequests",
            name="therapist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist_requests",
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
