# Generated by Django 4.2.4 on 2023-09-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_therapyrequests_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapyrequests",
            name="client",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="therapyrequests",
            name="therapist",
            field=models.CharField(max_length=30),
        ),
    ]
