# Generated by Django 4.2.4 on 2023-09-15 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_therapyrequests_client_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TherapyRequests",
            new_name="TherapyRequest",
        ),
    ]
