# Generated by Django 4.2.4 on 2023-09-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_rename_therapyrequests_therapyrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="qualifications",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
