# Generated by Django 4.2.4 on 2023-09-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_user_qualifications_user_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapyrequest",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
